/**
 * hotels.ts
 * ----------
 * Zentrale Liste aller Ziele / Hotels
 * Wird im BookingWizard importiert
 */

export const hotels: string[] = [

  // ===== Airports =====
  "Hurghada Airport",
  "Marsa Alam Airport",

  // ===== Cities =====
  "Aswan",
  "Luxor",
  "Marsa Alam town",
  "Berenice Town",
  "Hamata (town and harbour)",
  "El Gouna",
  "Sahl Hasheesh",

  // ===== Marsa Alam / Region =====
  "Abu Dabbab",
  "Akassia Sentido",
  "Akassia Swiss Resort",
  "Alam B&B Hostel",
  "Alexander the Great Resort",
  "Amarina Jannah Resort",
  "Amarina Queen Resort",
  "Aurora Bay Resort",
  "Beach Safari Resort",
  "Best Western Solitaire",
  "Blend Elphinstone",
  "Bliss Nada Beach Resort",
  "Blue Lagoon",
  "Blue Reef",
  "Blue Vision Diving Hotel",
  "Brayka Bay",
  "Casa Blue Resort",
  "Casa Mare Resort",
  "Cleopatra",
  "Club Calimera Akassia",
  "Concorde Moreen Beach",
  "Coral Hills Resort",
  "Crystal Beach Resort",
  "Deep Blue Inn",
  "Deep South Eco Lodge",
  "Diamond Beach by pearl resort",
  "Diving Station – Reef Villa",
  "Dolphin Continental Hotel",
  "Dolphin Hotel Tourism",
  "Dream Lagoon",
  "Dreams Beach Resort",
  "Eco Lodge Bedouin Valley",
  "El Quseir Hotel",
  "Falamenco Beach",
  "Fanadir Resort",
  "Fantazia",
  "Floriana Dream Lagoon",
  "Floriana Emerald Lagoon",
  "Gemma Beach Resort",
  "Gorgonia Resort",
  "Hilton Nubian",
  "Hotelux Oriental Coast",
  "Jaz Alaya",
  "Jaz Amara",
  "Jaz Costa Mares",
  "Jaz Lamaya Resort",
  "Jaz Maraya Resort",
  "Jaz Neo Dar El Madina",
  "Jaz neo Grand Marsa (Resta)",
  "Jaz neo Reef",
  "Jaz Riviera",
  "Jaz Samaya",
  "Jaz Solaya",
  "Julia Beach",
  "Laguna Beach Resort",
  "Lahami Bay",
  "Lazuli Hotel/Beach Resort",
  "Light House Marsa Alam",
  "Malikia Resort Abu Dabbab",
  "Mangrove Bay Resort",
  "Marina Lodge Port Ghalib",
  "Marina residence port ghalib",
  "Marsa Nakari",
  "Marsa Shagara Village",
  "Moon Resort/Moon Azur",
  "Movenpick El Qusier",
  "Novotel Resort",
  "Oasis",
  "Onatti Beach",
  "Oriental Bay",
  "Oyster Bay Beach",
  "Paradise club shoni bay resort",
  "Pensee (Royal Garden) Beach",
  "Pickalbatros Oasis",
  "Pickalbatros Palace",
  "Pickalbatros Sands",
  "Pickalbatros Villaggio-Portofino",
  "Pickalbatros Vita Portofino",
  "Pickalbatross Sea World",
  "Port Ghalib Marina",
  "Protels Crystal Beach Resort",
  "Radisson Marina Port Ghalib",
  "Rayhana Guest House",
  "Red Sea Hotel Marsa Alam",
  "Reef House Marsa Alam",
  "Reef Oasis Suakin",
  "Rohanou Beach Resort & Ecolodge",
  "Roots Red Sea",
  "Royal Brayka Beach Resort",
  "Sataya Resort",
  "Sea Dream Hotel El Quseir",
  "Sea View House Marsa Alam",
  "Sentido Reef Oasis Suakin",
  "Serina Beach",
  "Shams Alam",
  "Silver Beach Redsea Resort",
  "Solymar Reef",
  "Steigenberger Coraya",
  "Steigenberger Resort Alaya",
  "Sultan Palace",
  "Sunrise Anjum",
  "Swissotel Resort ElQusir",
  "Swisstouch Oriental Resort",
  "Three Corners Equinox El Naaba",
  "Three Corners Fayrouz",
  "Three Corners Happy Life",
  "Three Corners Sea Beach",
  "True Beach Resort",
  "Tui Blue Samaya",
  "Utopia Resort",
  "Veraclub Emerald Lagoon",
  "Wadi Lahami Village",
  "Wadi Lahmy Azur",
  "Wadi Sabarah Lodge",
  "Zabargad",

  // ===== Routes =====
  "Cairo (one way)",
  "Cairo (return same day)",
  "Luxor (one way)",
  "Luxor (return same day)"

];